baseURL = 'https://blog.alkali.top/'
languageCode = 'zh-CN'
title = "ALKALiKong's blog"
theme = 'hugo-theme-stack'

[params]
[params.sidebar]
emoji = ""
subtitle = "Welcome to my blog"

[params.sidebar.avatar]
enabled = true
local = true
src = "img/avatar.png"

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = -100
    [menu.main.params]
      icon = "home"
  
  [[menu.main]]
    name = "GitHub"
    url = "https://github.com/ALKALiKong233"
    weight = -90
    [menu.main.params]
      icon = "brand-github"
      newTab = true
